### PR TITLE
Fix up Setting updating with optional update params

### LINKED ISSUE #211: Updating any settings sets many to defaults
Due to the way that the settings updates are handles, updating, for example, the home page template will cause many other settings, including things like permanent email, to revert to the defaults.

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**
Previously, several of the options "default" to falsey/nil
when the parameter is not provided for update. This is the
result of a simplistic edit form that did not handle the
falsey/nil value in the actual HTML form, instead defaulting
to falsey/nil when the value was not supplied. This causes
errors after the Settings update pages were split into sections.

Closes #211

### CODE REVIEW

File: spec/controllers/admin/users_controller_spec.rb [hunk 1]
```diff
@@ -219,7 +219,7 @@
         it 'can add a user to a group' do
           post(:update, params: { id: user.id, user: { group_ids: [admin_group.id, user_group.id] } })
           user.reload
-          expect(user.groups.pluck(:name)).to eq %w[administrators users]
+          expect(user.groups.pluck(:name).sort).to eq %w[administrators users]
```
Comment (ChrisMacNaughton) [inline spec/controllers/admin/users_controller_spec.rb:222]: For some reason, this test started failing with the second new test above (`doesn't reset expire_after when changing HTML title`)
